services:
  db:
    image: postgres:12-alpine
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - production
  web:
    build: .
    command: "puma"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db 
    profiles:
      - production
  dev:
    build: .
    command: "puma"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"