default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  # host: <%= ENV['DB_HOST'] %>
  # username: tuesday_development
  # password: <%= ENV['DEV_DB_PASSWORD'] %>
  # database: tuesday_development

test:
  <<: *default
  database: tuesday_test
  
production:
  <<: *default
  database: tuesday_production